import { ChainId, ChainInfo } from "../types";

export const chainInfo: { [chainId in ChainId]: ChainInfo } = {
  [ChainId.MAINNET]: {
    label: "Ethereum",
    appUrl: "https://looksrare.org",
    explorer: "https://etherscan.io",
    rpcUrl: "https://eth-mainnet.g.alchemy.com/v2",
    baseApiUrl: "https://graphql.looksrare.org",
    osApiUrl: "https://api.opensea.io",
    cdnUrl: "https://static.looksnice.org",
    rewardsSubgraphUrl: "https://api.thegraph.com/subgraphs/name/looksrare/looks-distribution",
    cloudinaryUrl: "https://looksrare.mo.cloudinary.net",
    wsUrl: "wss://ws.looksrare.org/ws",
  },
  [ChainId.GOERLI]: {
    label: "Goerli",
    appUrl: "https://goerli.looksrare.org",
    explorer: "https://goerli.etherscan.io",
    rpcUrl: "https://eth-goerli.g.alchemy.com/v2",
    baseApiUrl: "https://graphql-goerli.looksrare.org",
    osApiUrl: "https://testnets-api.opensea.io",
    cdnUrl: "https://static-goerli.looksnice.org",
    rewardsSubgraphUrl: "https://api.thegraph.com/subgraphs/name/0xjurassicpunk/looks-distribution",
    cloudinaryUrl: "https://looksrare.mo.cloudinary.net/goerli",
    wsUrl: "wss://ws-goerli.looksrare.org/ws",
  },
  [ChainId.SEPOLIA]: {
    label: "Sepolia",
    appUrl: "https://sepolia.looksrare.org",
    explorer: "https://sepolia.etherscan.io",
    rpcUrl: "https://eth-sepolia.g.alchemy.com/v2",
    baseApiUrl: "https://graphql-sepolia.looksrare.org",
    osApiUrl: "https://testnets-api.opensea.io",
    cdnUrl: "https://static-sepolia.looksnice.org",
    rewardsSubgraphUrl: "https://api.thegraph.com/subgraphs/name/0xjurassicpunk/looks-distribution",
    cloudinaryUrl: "https://looksrare.mo.cloudinary.net/sepolia",
    wsUrl: "wss://ws-sepolia.looksrare.org/ws",
  },
  [ChainId.ARB_MAINNET]: {
    label: "Arbitrum",
    appUrl: "https://looksrare.org",
    explorer: "https://arbiscan.io",
    rpcUrl: "https://arb-mainnet.g.alchemy.com/v2",
    baseApiUrl: "https://graphql.looksrare.org",
    osApiUrl: "https://api.opensea.io",
    cdnUrl: "https://static.looksnice.org",
    rewardsSubgraphUrl: "https://api.thegraph.com/subgraphs/name/looksrare/looks-distribution",
    cloudinaryUrl: "https://looksrare.mo.cloudinary.net",
    wsUrl: "wss://ws.looksrare.org/ws",
  },
  [ChainId.ARB_SEPOLIA]: {
    label: "Arbitrum Sepolia",
    appUrl: "https://sepolia.looksrare.org",
    explorer: "https://sepolia.arbiscan.io",
    rpcUrl: "https://arb-sepolia.g.alchemy.com/v2",
    baseApiUrl: "https://graphql-sepolia.looksrare.org",
    osApiUrl: "https://testnets-api.opensea.io",
    cdnUrl: "https://static-sepolia.looksnice.org",
    rewardsSubgraphUrl: "https://api.thegraph.com/subgraphs/name/0xjurassicpunk/looks-distribution",
    cloudinaryUrl: "https://looksrare.mo.cloudinary.net/sepolia",
    wsUrl: "wss://ws-sepolia.looksrare.org/ws",
  },
  [ChainId.HARDHAT]: {
    label: "Hardhat",
    appUrl: "http://localhost:3000",
    explorer: "https://etherscan.io",
    rpcUrl: "http://127.0.0.1:8545",
    baseApiUrl: "http://localhost:4000",
    osApiUrl: "https://testnets-api.opensea.io",
    cdnUrl: "https://via.placeholder.com",
    rewardsSubgraphUrl: "https://api.thegraph.com/subgraphs/name/0xjurassicpunk/looks-distribution",
    cloudinaryUrl: "",
    wsUrl: "ws://localhost:5001/ws",
  },
};
